### ISSUE TITLE
libfragmentzip error - dyld: Symbol not found

### ISSUE THREAD

**Issue by ethanjansen** [tihmstar/tsschecker#142]
Version 285 of tsschecker
Version 47 of libfragmentzip

I get this error with: `tsschecker -d iPhone12,3 -i 13.0`

> dyld: lazy symbol binding failed: Symbol not found: _crc32_z
  Referenced from: /usr/local/lib/libfragmentzip.0.dylib
  Expected in: flat namespace

>dyld: Symbol not found: _crc32_z
  Referenced from: /usr/local/lib/libfragmentzip.0.dylib
  Expected in: flat namespace

>Abort trap: 6

I get this error with: `tsschecker -d iPhone9,2 -i 13.0`

>[Error] [LFZP] fialed to download file (-1)
tsschecker(83228,0x7fff982873c0) malloc: *** error for object 0x7fd0d48176d6: Pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by tihmstar** [comment]
How did you compile libfragmentzip?

**Comment by ethanjansen** [comment]
Just used autogen and makefile.

**Comment by ethanjansen** [comment]
After updating libfragmentzip to 49 both of the previous errors are gone.
It succeeds when using iPhone12,3.
However iPhone9,2 and 8,1 still fail to download with LFZP just without the freed pointer error.

**Comment by tihmstar** [comment]
pushed another update to libfragmentzip which should fix that.
please open an issue on libfragmentzip repo next time if you feel like it's a problem in libfragmentzip rather than tsschecker
